:development: &defaults
  :adapter: mysql
  :database: goplay_dev
  :username: goplay
  :password: gp0102
  :host: localhost

:test:
  <<: *defaults
  :database: goplay_test

:production:
  <<: *defaults
  :database: goplay
  :password: gp0102$